(()=>{'use strict';
const U='https://tsvjulkvmrscgqajttra.supabase.co',K='sb_publishable_NVFEYqGjxqBeHb99FwKWjw_nd6YIE1h';
const A=window.supabase.createClient(U,K,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}}),$=id=>document.getElementById(id);
let s=null;
const statusMap={open:'Aberto',matched:'Com profissionais',accepted:'Aceite',completed:'Concluído',cancelled:'Cancelado'};
function close(){ $('accountModal')?.classList.remove('open') }
function tab(name){document.querySelectorAll('.account-tab').forEach(b=>b.classList.toggle('on',b.dataset.accountTab===name));document.querySelectorAll('.account-panel').forEach(p=>p.classList.toggle('on',p.dataset.accountPanel===name));if(name==='profile')loadProfile();if(name==='requests')loadRequests();if(name==='professional')loadProfessional()}
async function ensure(){const r=await A.auth.getSession();s=r.data.session;const c=$('accountCta');if(c)c.classList.toggle('on',!!s);return s}
async function open(name='profile'){if(!await ensure()){ $('authBtn')?.click();return }$('accountModal').classList.add('open');tab(name)}
async function loadProfile(){if(!s)return;const r=await A.from('profiles').select('display_name,phone,account_type').eq('id',s.user.id).maybeSingle(),p=r.data||{};$('accountName').value=p.display_name||'';$('accountPhone').value=p.phone||'';$('accountEmail').textContent=s.user.email||'';$('accountType').textContent=p.account_type==='both'?'Cliente + profissional':p.account_type==='professional'?'Profissional':'Cliente'}
async function saveProfile(e){e.preventDefault();const name=$('accountName').value.trim();if(name.length<2){$('accountProfileMsg').textContent='Indica um nome válido.';return}const r=await A.from('profiles').update({display_name:name,phone:$('accountPhone').value.trim()||null,updated_at:new Date().toISOString()}).eq('id',s.user.id);$('accountProfileMsg').textContent=r.error?r.error.message:'Dados guardados ✓'}
async function cancelRequest(id){if(!s||!id)return;if(!window.confirm('Retirar este pedido? Ele deixará de aparecer nos pedidos ativos.'))return;const r=await A.from('service_requests').update({status:'cancelled',updated_at:new Date().toISOString()}).eq('id',id).eq('client_id',s.user.id).in('status',['open','matched']);if(r.error){window.alert('Não foi possível retirar o pedido.');return}await loadRequests()}
async function loadRequests(){if(!s)return;$('accountRequests').innerHTML='<div class="account-empty">A carregar…</div>';const r=await A.from('service_requests').select('id,description,city,status,created_at,skill_id').eq('client_id',s.user.id).neq('status','cancelled').order('created_at',{ascending:false});if(r.error){$('accountRequests').innerHTML='<div class="account-empty">Não foi possível carregar os pedidos.</div>';return}const rows=r.data||[];if(!rows.length){$('accountRequests').innerHTML='<div class="account-empty">Não tens pedidos ativos. Quando guardares um pedido, ele aparece aqui.</div>';return}const ids=[...new Set(rows.map(x=>x.skill_id).filter(Boolean))],sr=ids.length?await A.from('skills').select('id,name').in('id',ids):{data:[]},m=new Map((sr.data||[]).map(x=>[x.id,x.name]));$('accountRequests').innerHTML=rows.map(x=>`<div class="account-item request-item"><strong>${escapeHtml(m.get(x.skill_id)||'Pedido de serviço')}</strong><small>${escapeHtml(x.description)}${x.city?' · '+escapeHtml(x.city):''}</small><div class="request-footer"><span class="status-pill">${statusMap[x.status]||x.status}</span>${['open','matched'].includes(x.status)?`<button class="request-remove" type="button" data-remove-request="${x.id}">Retirar pedido</button>`:''}</div></div>`).join('');document.querySelectorAll('[data-remove-request]').forEach(b=>b.onclick=()=>cancelRequest(b.dataset.removeRequest))}
async function loadProfessional(){if(!s)return;$('accountProfessional').innerHTML='<div class="account-empty">A carregar…</div>';const [p,l,m]=await Promise.all([A.from('professional_profiles').select('public_name,headline,city,is_public,is_available').eq('user_id',s.user.id).maybeSingle(),A.from('professional_skills').select('skill_id').eq('professional_id',s.user.id),A.from('professional_memberships').select('status,trial_ends_at').eq('user_id',s.user.id).maybeSingle()]);if(!p.data){$('accountProfessional').innerHTML='<div class="account-empty">Ainda tens apenas conta de cliente. Podes ativar o modo profissional quando quiseres e os 60 dias gratuitos só começam quando guardares o primeiro perfil.</div><button class="btn primary" id="accountMakePro" type="button">Tornar-me profissional</button>';$('accountMakePro').onclick=()=>{close();$('proCta')?.click()};return}const ids=(l.data||[]).map(x=>x.skill_id),sr=ids.length?await A.from('skills').select('id,name').in('id',ids):{data:[]},skills=(sr.data||[]).map(x=>x.name),trial=m.data?.status==='trial'&&m.data?.trial_ends_at?Math.max(0,Math.ceil((new Date(m.data.trial_ends_at)-Date.now())/86400000)):null;$('accountProfessional').innerHTML=`<div class="account-summary"><div class="summary-card"><strong>${p.data.is_public?'Publicado':'Privado'}</strong><span>Estado do perfil</span></div><div class="summary-card"><strong>${trial!==null?trial+' dias':(m.data?.status||'Sem plano')}</strong><span>Plano profissional</span></div></div><div class="account-item"><strong>${escapeHtml(p.data.public_name||'Perfil profissional')}</strong><small>${escapeHtml(p.data.headline||'')}${p.data.city?' · '+escapeHtml(p.data.city):''}</small><div class="pro-skill-list">${skills.map(v=>`<span class="pro-skill-chip">${escapeHtml(v)}</span>`).join('')}</div></div><button class="btn primary" id="accountEditPro" type="button">Editar perfil profissional</button><h3>Serviços realizados</h3><div class="account-empty">Ainda não existe histórico de trabalhos concluídos porque o Faz Já ainda não associa cada pedido a um profissional. Essa será a próxima peça do fluxo profissional.</div>`;$('accountEditPro').onclick=()=>{close();$('proCta')?.click()}}
function escapeHtml(v){return String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
document.addEventListener('DOMContentLoaded',async()=>{await ensure();$('accountCta')?.addEventListener('click',()=>open('profile'));$('accountForm')?.addEventListener('submit',saveProfile);$('accountClose')?.addEventListener('click',close);document.querySelectorAll('.account-tab').forEach(b=>b.onclick=()=>tab(b.dataset.accountTab));$('navHome')?.addEventListener('click',()=>window.scrollTo({top:0,behavior:'smooth'}));$('navRequests')?.addEventListener('click',()=>open('requests'));$('navPro')?.addEventListener('click',()=>{if(s)$('proCta')?.click();else $('authBtn')?.click()});$('navAccount')?.addEventListener('click',()=>open('profile'));A.auth.onAuthStateChange(async(_e,ss)=>{s=ss;const c=$('accountCta');if(c)c.classList.toggle('on',!!s);if(!s)close()})})})();