(()=>{'use strict';
const URL='https://tsvjulkvmrscgqajttra.supabase.co',KEY='sb_publishable_NVFEYqGjxqBeHb99FwKWjw_nd6YIE1h';
if(!window.supabase?.createClient){document.body.innerHTML='<main style="padding:40px;font-family:system-ui"><h1>Faz Já</h1><p>Não foi possível iniciar a plataforma.</p></main>';return}
const S=window.supabase.createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}}),$=id=>document.getElementById(id);
let session=null,skills=[],cats=[],chosen=null,lastQ='',lastCity='',pending=null,mode='login',membership=null,plan=null;
const icons={casa:'<svg viewBox="0 0 24 24"><path d="M3 11.5 12 4l9 7.5"/><path d="M5.5 10v10h13V10"/><path d="M9.5 20v-6h5v6"/></svg>',automovel:'<svg viewBox="0 0 24 24"><path d="m5 16-1.2-4.2A2 2 0 0 1 5.7 9h12.6a2 2 0 0 1 1.9 2.8L19 16"/><path d="M5 16h14v3H5z"/><circle cx="7.5" cy="16" r="1"/><circle cx="16.5" cy="16" r="1"/><path d="m7 9 1.5-3h7L17 9"/></svg>',tecnologia:'<svg viewBox="0 0 24 24"><rect x="4" y="5" width="16" height="11" rx="2"/><path d="M8 20h8M12 16v4"/></svg>','limpeza e apoio':'<svg viewBox="0 0 24 24"><path d="m14 4 6 6"/><path d="M16.5 6.5 8 15"/><path d="M5 14c3 0 5 2 5 5H4c0-2 .3-3.5 1-5Z"/></svg>','beleza e bem-estar':'<svg viewBox="0 0 24 24"><circle cx="7" cy="7" r="2.5"/><circle cx="17" cy="7" r="2.5"/><path d="m9 9 8 8M15 9l-8 8"/></svg>',educacao:'<svg viewBox="0 0 24 24"><path d="m3 8 9-4 9 4-9 4-9-4Z"/><path d="M7 10.5V15c3 2 7 2 10 0v-4.5M21 8v6"/></svg>',eventos:'<svg viewBox="0 0 24 24"><path d="M12 3 9.5 8.5 4 11l5.5 2.5L12 19l2.5-5.5L20 11l-5.5-2.5L12 3Z"/></svg>',animais:'<svg viewBox="0 0 24 24"><circle cx="8" cy="7" r="2"/><circle cx="16" cy="7" r="2"/><circle cx="5" cy="12" r="2"/><circle cx="19" cy="12" r="2"/><path d="M8 18c0-3 2-5 4-5s4 2 4 5c0 2-1.5 3-4 3s-4-1-4-3Z"/></svg>','negocios e profissionais':'<svg viewBox="0 0 24 24"><rect x="4" y="7" width="16" height="12" rx="2"/><path d="M9 7V5h6v2M4 12h16M10 12v2h4v-2"/></svg>',transportes:'<svg viewBox="0 0 24 24"><path d="M3 6h12v10H3zM15 10h3l3 3v3h-6z"/><circle cx="7" cy="18" r="2"/><circle cx="18" cy="18" r="2"/></svg>'};
const kw=[['plumbing',['torneira','cano','fuga','autoclismo','entup']],['electrician',['eletric','tomada','disjuntor','sem luz']],['appliance-repair',['máquina de lavar','maquina de lavar','frigor','forno']],['computer-repair',['computador','portátil','portatil','windows','wifi']],['mechanic',['carro não pega','carro nao pega','motor','travões','travoes']],['home-cleaning',['limpeza','limpar casa']],['painting',['pintar','pintura']],['furniture-assembly',['montar móvel','montar movel','ikea']],['air-conditioning',['ar condicionado']],['gardening',['jardim','jardineiro']],['wordpress',['wordpress','woocommerce']],['web-development',['website','site','programador web']],['dog-walking',['passear cão','passear cao']],['moving',['mudança','mudanca']]];
const norm=v=>String(v||'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,''),esc=v=>String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function open(id){$(id).classList.add('open')}function close(id){$(id).classList.remove('open')}function toast(m){$('toast').textContent=m;$('toast').classList.add('on');setTimeout(()=>$('toast').classList.remove('on'),2600)}
function sid(){let v=localStorage.fazja_sid;if(!v){v=crypto.randomUUID();localStorage.fazja_sid=v}return v}function infer(t){t=norm(t);for(const[slug,terms]of kw)if(terms.some(k=>t.includes(norm(k))))return skills.find(s=>s.slug===slug);return skills.find(s=>t.includes(norm(s.name)))||chosen}
function price(p){if(p.price_unit==='quote'||p.base_price==null)return'Sob orçamento';const v=Number(p.base_price).toLocaleString('pt-PT',{style:'currency',currency:'EUR'});return p.price_unit==='hour'?v+'/h':p.price_unit==='visit'?v+' deslocação':'Desde '+v}
function categoryIcon(name){return icons[norm(name)]||'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="8"/><path d="M8 12h8M12 8v8"/></svg>'}
function renderCategories(){$('categoryGrid').innerHTML=cats.map(c=>`<button class="category-card" data-cat="${c.id}"><span class="cat-icon">${categoryIcon(c.name)}</span><span class="cat-name">${esc(c.name)}</span><span class="cat-arrow">↗</span></button>`).join('');document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>selectCategory(Number(b.dataset.cat)))}
function selectCategory(id){chosen=null;document.querySelectorAll('[data-cat]').forEach(b=>b.classList.toggle('active',Number(b.dataset.cat)===id));const c=cats.find(x=>x.id===id),list=skills.filter(s=>s.category_id===id);$('servicesTitle').textContent=c?.name||'Serviços';$('serviceChips').innerHTML=list.map(s=>`<button class="service-chip" data-skill="${s.id}">${esc(s.name)}</button>`).join('');$('servicesPanel').classList.remove('hidden');document.querySelectorAll('[data-skill]').forEach(b=>b.onclick=()=>pickSkill(Number(b.dataset.skill)));$('servicesPanel').scrollIntoView({behavior:'smooth',block:'nearest'})}
function pickSkill(id){chosen=skills.find(s=>s.id===id);document.querySelectorAll('[data-skill]').forEach(b=>b.classList.toggle('active',Number(b.dataset.skill)===id));if(chosen){$('problem').value=chosen.name;$('problem').focus()}}
async function loadMembership(){membership=null;if(!session)return;const{data}=await S.from('professional_memberships').select('user_id,status,trial_started_at,trial_ends_at,current_period_end,cancel_at_period_end').eq('user_id',session.user.id).maybeSingle();membership=data||null}
function mState(){if(!membership)return'none';if(membership.status==='trial'&&new Date(membership.trial_ends_at)>new Date())return'trial';if(membership.status==='active'&&(!membership.current_period_end||new Date(membership.current_period_end)>new Date()))return'active';return'expired'}
function daysLeft(){if(!membership?.trial_ends_at)return 0;return Math.max(0,Math.ceil((new Date(membership.trial_ends_at)-Date.now())/86400000))}
function renderPlan(){const s=mState(),el=$('planStatus');if(s==='trial')el.innerHTML=`<strong>Período gratuito ativo</strong><span>Restam cerca de ${daysLeft()} dias. O teu perfil pode aparecer nas pesquisas enquanto o período estiver ativo.</span>`;else if(s==='active')el.innerHTML='<strong>Plano profissional ativo</strong><span>O teu perfil pode aparecer nas pesquisas.</span>';else if(s==='expired')el.innerHTML='<strong>Período gratuito terminado</strong><span>O perfil fica guardado, mas deixa de aparecer publicamente até existir uma subscrição ativa.</span>';else el.innerHTML='<strong>2 meses grátis</strong><span>O período começa quando criares o primeiro perfil profissional.</span>'}
function ui(){const s=mState();$('authBtn').textContent=session?'Sair':'Entrar';$('proCta').textContent=!session?'Quero prestar serviços':s==='trial'||s==='active'?'Área profissional':s==='expired'?'Reativar profissional':'Tornar-me profissional'}
async function init(){document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('.modal').classList.remove('open'));$('homeBtn').onclick=()=>window.scrollTo({top:0,behavior:'smooth'});const{data:{session:s}}=await S.auth.getSession();session=s;const[a,b,p]=await Promise.all([S.from('service_categories').select('id,name,sort_order').order('sort_order'),S.from('skills').select('id,category_id,slug,name').order('name'),S.from('professional_plan').select('id,name,trial_days,monthly_price_eur,billing_enabled').eq('id','standard').maybeSingle()]);if(a.error||b.error)throw new Error('Falha ao carregar serviços');cats=a.data||[];skills=b.data||[];plan=p.data||null;await loadMembership();ui();renderCategories();$('pskills').innerHTML=skills.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('');S.auth.onAuthStateChange(async(_e,s2)=>{session=s2;await loadMembership();ui();if(s2&&pending){const p=pending;pending=null;close('authModal');p==='pro'?openPro():openReq()}})}
$('searchForm').onsubmit=async e=>{e.preventDefault();lastQ=$('problem').value.trim();lastCity=$('city').value.trim();chosen=infer(lastQ);$('results').classList.remove('hidden');$('cards').innerHTML='';$('empty').classList.add('hidden');if(!chosen){$('matchText').textContent='Escolhe uma categoria ou descreve melhor o que precisas';$('empty').classList.remove('hidden');await log(0);return}$('matchText').textContent=chosen.name;const l=await S.from('professional_skills').select('professional_id').eq('skill_id',chosen.id),ids=[...new Set((l.data||[]).map(x=>x.professional_id))];let pros=[];if(ids.length){let q=S.from('professional_profiles').select('user_id,public_name,headline,bio,city,base_price,price_unit,is_available,verification_status').in('user_id',ids).eq('is_public',true);if(lastCity)q=q.ilike('city',lastCity);const r=await q.order('is_available',{ascending:false});pros=r.data||[]}await log(pros.length);if(!pros.length)$('empty').classList.remove('hidden');else{$('cards').innerHTML=pros.map(p=>`<article class="pro-card"><div class="pro-top"><div class="avatar">${esc((p.public_name||'F').charAt(0).toUpperCase())}</div><div><h3>${esc(p.public_name||'Profissional Faz Já')}</h3><div class="meta">${esc(p.headline||chosen.name)} · ${esc(p.city||'Zona por indicar')}</div></div></div><div class="badges"><span class="badge ${p.is_available?'on':''}">${p.is_available?'● Disponível agora':'A combinar'}</span><span class="badge">${p.verification_status==='verified'?'✓ Verificado':'Novo na plataforma'}</span></div><p class="bio">${esc(p.bio||'Sem apresentação ainda.')}</p><div class="pro-foot"><strong>${price(p)}</strong><button class="btn primary ask">Pedir serviço</button></div></article>`).join('');document.querySelectorAll('.ask').forEach(b=>b.onclick=()=>need('request'))}$('results').scrollIntoView({behavior:'smooth',block:'start'})};
async function log(n){await S.from('search_events').insert({session_id:sid(),user_id:session?.user?.id||null,query:lastQ||chosen?.name||'Pesquisa',resolved_skill_id:chosen?.id||null,city:lastCity||null,result_count:n})}
function need(a){pending=a;if(!session){setMode('signup');$('type').value=a==='pro'?'professional':'client';open('authModal');return}pending=null;a==='pro'?openPro():openReq()}
$('saveDemand').onclick=()=>need('request');$('proCta').onclick=()=>need('pro');$('authBtn').onclick=async()=>{if(session){await S.auth.signOut();toast('Sessão terminada')}else{setMode('login');open('authModal')}};document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));
function setMode(m){mode=m;document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('on',b.dataset.mode===m));document.querySelectorAll('.signup').forEach(x=>x.classList.toggle('hidden',m!=='signup'));$('authTitle').textContent=m==='signup'?'Criar conta':'Entrar';$('authSubmit').textContent=m==='signup'?'Criar conta':'Entrar';$('authMsg').textContent=''}
$('authForm').onsubmit=async e=>{e.preventDefault();let email=$('email').value.trim(),password=$('password').value,err,data;if(mode==='signup'){if($('name').value.trim().length<2){$('authMsg').className='msg err';$('authMsg').textContent='Indica o teu nome.';return}if(!$('consent').checked){$('authMsg').className='msg err';$('authMsg').textContent='Aceita os Termos e a Política de Privacidade.';return}const wantsPro=$('type').value==='professional';if(wantsPro)pending='pro';({data,error:err}=await S.auth.signUp({email,password,options:{data:{display_name:$('name').value.trim(),account_type:$('type').value,beta_terms_version:'2026-08-27'}}}));if(!err&&!data.session){$('authMsg').className='msg ok';$('authMsg').textContent=wantsPro?'Conta criada. Confirma o email e depois completa o perfil profissional para iniciar os 60 dias gratuitos.':'Conta criada. Confirma o email e depois volta aqui para entrar.';pending=null;return}}else({error:err}=await S.auth.signInWithPassword({email,password}));if(err){$('authMsg').className='msg err';$('authMsg').textContent=err.message}else{close('authModal');toast('Bem-vindo ao Faz Já')}};
function openReq(){$('reqDesc').value=lastQ||chosen?.name||'';$('reqCity').value=lastCity;open('requestModal')}$('requestForm').onsubmit=async e=>{e.preventDefault();if(!session)return need('request');const d=$('reqDesc').value.trim(),c=$('reqCity').value.trim();const{error}=await S.from('service_requests').insert({client_id:session.user.id,skill_id:chosen?.id||infer(d)?.id||null,raw_query:lastQ||d,description:d,city:c});$('reqMsg').className='msg '+(error?'err':'ok');$('reqMsg').textContent=error?error.message:'Pedido guardado ✓';if(!error)setTimeout(()=>close('requestModal'),700)};
async function openPro(){if(!session)return need('pro');await loadMembership();renderPlan();const uid=session.user.id,[p,l]=await Promise.all([S.from('professional_profiles').select('*').eq('user_id',uid).maybeSingle(),S.from('professional_skills').select('skill_id').eq('professional_id',uid)]),pro=p.data||{};$('pname').value=pro.public_name||'';$('headline').value=pro.headline||'';$('bio').value=pro.bio||'';$('pcity').value=pro.city||'';$('price').value=pro.base_price??'';$('available').checked=!!pro.is_available;$('public').checked=!!pro.is_public;const ids=(l.data||[]).map(x=>String(x.skill_id));[...$('pskills').options].forEach(o=>o.selected=ids.includes(o.value));open('proModal')}
$('proForm').onsubmit=async e=>{e.preventDefault();const ids=[...$('pskills').selectedOptions].map(o=>Number(o.value));if(!ids.length){$('proMsg').className='msg err';$('proMsg').textContent='Escolhe pelo menos um serviço.';return}const uid=session.user.id,had=!!membership,payload={user_id:uid,public_name:$('pname').value.trim(),headline:$('headline').value.trim()||null,bio:$('bio').value.trim()||null,city:$('pcity').value.trim(),service_radius_km:15,base_price:$('price').value===''?null:Number($('price').value),price_unit:'from',is_available:$('available').checked,is_public:$('public').checked,updated_at:new Date().toISOString()},r=await S.from('professional_profiles').upsert(payload,{onConflict:'user_id'});if(r.error){$('proMsg').className='msg err';$('proMsg').textContent=r.error.message;return}await S.from('professional_skills').delete().eq('professional_id',uid);const ins=await S.from('professional_skills').insert(ids.map((skill_id,i)=>({professional_id:uid,skill_id,is_primary:i===0})));await loadMembership();ui();renderPlan();$('proMsg').className='msg '+(ins.error?'err':'ok');$('proMsg').textContent=ins.error?ins.error.message:(!had&&mState()==='trial'?`Perfil criado ✓ Tens cerca de ${daysLeft()} dias gratuitos.`:($('public').checked?'Perfil publicado ✓':'Perfil guardado ✓'))};
const legal={privacy:{title:'Política de Privacidade',body:'O Faz Já utiliza os dados necessários para criar contas, apresentar perfis profissionais, guardar pedidos e melhorar a pesquisa de serviços. A autenticação e a base de dados usam infraestrutura Supabase. Não vendemos dados pessoais a anunciantes.'},terms:{title:'Termos de Utilização',body:'A conta de utilizador é gratuita. O modo profissional inclui 60 dias gratuitos a partir da criação do primeiro perfil profissional. Depois desse período, o perfil profissional deixa de aparecer publicamente sem uma subscrição ativa. O valor da mensalidade será apresentado antes da ativação do pagamento. Cada profissional é responsável pela informação do perfil, qualificações, preços e execução do serviço.'}};document.querySelectorAll('[data-legal]').forEach(b=>b.onclick=()=>{const d=legal[b.dataset.legal];$('legalTitle').textContent=d.title;$('legalBody').textContent=d.body;open('legalModal')});
init().catch(err=>{console.error(err);$('categoryGrid').innerHTML='<div class="loading-card">Não foi possível carregar os serviços. Recarrega a página.</div>'});
})();