import { supabase as S } from './supabase.js';
import { getSession } from './auth.js';
import { escapeHtml } from './utils.js';

const $ = (id) => document.getElementById(id);
let currentRequest = null;
let currentProposal = null;
let currentContact = null;
let channel = null;
let onChanged = () => {};
let bound = false;

const statusMap = { open:'Em conversa', matched:'Em conversa', accepted:'Proposta aceite', in_progress:'Em curso', completed:'Concluído', declined:'Profissional desistiu', cancelled:'Cancelado' };

function closeChat(){ $('chatModal')?.classList.remove('open'); if(channel){S.removeChannel(channel);channel=null} currentRequest=null;currentProposal=null;currentContact=null }
function role(){ const s=getSession(); if(!s||!currentRequest)return null; return s.user.id===currentRequest.client_id?'client':'professional' }
function fullAddress(c=currentContact){ return [c?.service_address_line1,c?.service_address_line2,c?.service_postal_code,c?.service_city].filter(Boolean).join(', ') }
function wazeUrl(){ const a=fullAddress(); return a?`https://www.waze.com/ul?q=${encodeURIComponent(a)}&navigate=yes`:'' }
function money(v){ return Number(v||0).toLocaleString('pt-PT',{style:'currency',currency:'EUR'}) }

function renderContact(){const b=$('chatPrivateData');if(!b||!currentRequest)return;if(role()==='professional'){const p=currentContact?.client_phone,a=fullAddress();b.innerHTML=`<strong>Dados privados deste pedido</strong><span>Cliente anónimo</span>${p?`<a href="tel:${escapeHtml(String(p).replace(/[^+\d]/g,''))}">${escapeHtml(p)}</a>`:'<span>Telefone não indicado</span>'}${a?`<span>${escapeHtml(a)}</span>`:'<span>Morada ainda não indicada</span>'}`;return}const n=currentContact?.professional_name||'Profissional Faz Já',p=currentContact?.professional_phone;b.innerHTML=`<strong>${escapeHtml(n)}</strong>${p?`<a href="tel:${escapeHtml(String(p).replace(/[^+\d]/g,''))}">${escapeHtml(p)}</a>`:'<span>Contacto disponível através do chat</span>'}`}
function renderProposal(){const b=$('chatProposal');if(!b)return;if(!currentProposal){b.innerHTML='<div class="chat-empty">Ainda não existe uma proposta formal.</div>';return}b.innerHTML=`<div class="proposal-card"><div><small>PROPOSTA</small><strong>${money(currentProposal.amount_eur)}</strong></div><span class="status-pill">${currentProposal.status==='pending'?'A aguardar decisão':currentProposal.status==='accepted'?'Aceite':currentProposal.status==='rejected'?'Recusada':'Retirada'}</span>${currentProposal.details?`<p>${escapeHtml(currentProposal.details)}</p>`:''}</div>`}
function renderMessages(ms){const s=getSession(),c=$('chatMessages');if(!c||!s)return;c.innerHTML=ms.length?ms.map(m=>m.kind==='system'?`<div class="chat-system">${escapeHtml(m.body)}</div>`:`<div class="chat-message ${m.sender_id===s.user.id?'mine':''}"><small>${m.sender_id===s.user.id?'Tu':role()==='client'?'Profissional':'Cliente'}</small><p>${escapeHtml(m.body)}</p></div>`).join(''):'<div class="chat-empty">Escreve a primeira mensagem.</div>';c.scrollTop=c.scrollHeight}

function renderActions(){const a=$('chatActions'),f=$('proposalForm');if(!a||!f||!currentRequest)return;const r=role(),terminal=['completed','cancelled','declined'].includes(currentRequest.status);f.classList.add('hidden');$('chatInput').disabled=terminal;$('chatSend').disabled=terminal;if(terminal){a.innerHTML='<span class="chat-terminal">Este pedido está encerrado.</span>';return}if(r==='client'){const pending=currentProposal?.status==='pending';a.innerHTML=`<button class="chat-action accept" id="acceptProposal" type="button" ${pending?'':'disabled'}>Aceitar proposta</button><button class="chat-action reject" id="rejectProposal" type="button" ${pending?'':'disabled'}>Recusar proposta</button><button class="chat-action danger" id="cancelService" type="button">Desistir do serviço</button>`;$('acceptProposal')?.addEventListener('click',()=>decide('accepted'));$('rejectProposal')?.addEventListener('click',()=>decide('rejected'));$('cancelService')?.addEventListener('click',cancelService);return}if(['accepted','in_progress'].includes(currentRequest.status)){const w=wazeUrl();a.innerHTML=`${w?`<a class="chat-action go" href="${w}" target="_blank" rel="noopener">Ir até</a>`:'<button class="chat-action go" disabled type="button">Ir até</button>'}<button class="chat-action accept" id="completeService" type="button">Pedido concluído</button><button class="chat-action danger" id="withdrawRequest" type="button">Desistir do pedido</button>`;$('completeService')?.addEventListener('click',completeService);$('withdrawRequest')?.addEventListener('click',withdrawRequest);return}a.innerHTML='<button class="chat-action proposal" id="showProposalForm" type="button">Enviar proposta</button><button class="chat-action danger" id="withdrawRequest" type="button">Desistir do pedido</button>';$('showProposalForm')?.addEventListener('click',()=>f.classList.toggle('hidden'));$('withdrawRequest')?.addEventListener('click',withdrawRequest)}

async function refresh(){if(!currentRequest)return;const id=currentRequest.id,[r,m,p,c]=await Promise.all([S.from('service_requests').select('id,client_id,professional_id,description,city,status,created_at,skill_id').eq('id',id).single(),S.from('service_messages').select('id,sender_id,kind,body,created_at').eq('request_id',id).order('created_at'),S.from('service_proposals').select('id,amount_eur,details,status,created_at,decided_at').eq('request_id',id).order('created_at',{ascending:false}).limit(1),S.rpc('service_request_contact',{p_request_id:id})]);if(r.error)throw r.error;if(m.error)throw m.error;if(p.error)throw p.error;currentRequest=r.data;currentProposal=p.data?.[0]||null;currentContact=c.error?null:c.data;$('chatTitle').textContent=currentRequest.description||'Pedido de serviço';$('chatStatus').textContent=statusMap[currentRequest.status]||currentRequest.status;renderContact();renderProposal();renderMessages(m.data||[]);renderActions()}
async function sendMessage(e){e.preventDefault();const s=getSession(),i=$('chatInput'),body=i?.value.trim();if(!s||!currentRequest||!body)return;const q=await S.from('service_messages').insert({request_id:currentRequest.id,sender_id:s.user.id,kind:'message',body});if(q.error){alert('Não foi possível enviar a mensagem.');return}i.value=''}
async function sendProposal(e){e.preventDefault();const amount=Number($('proposalAmount')?.value||0),details=$('proposalDetails')?.value.trim()||'';const q=await S.rpc('send_service_proposal',{p_request_id:currentRequest.id,p_amount:amount,p_details:details||null});if(q.error){alert(q.error.message.includes('pending proposal')?'Já existe uma proposta à espera de decisão.':'Não foi possível enviar a proposta.');return}$('proposalForm')?.reset();$('proposalForm')?.classList.add('hidden');await refresh();onChanged()}
async function decide(d){if(!currentProposal)return;const q=await S.rpc('client_decide_service_proposal',{p_proposal_id:currentProposal.id,p_decision:d});if(q.error){alert('Não foi possível registar a decisão.');return}await refresh();onChanged()}
async function cancelService(){if(!currentRequest||!confirm('Desistir deste serviço?'))return;const q=await S.rpc('client_cancel_service_request',{p_request_id:currentRequest.id});if(q.error){alert('Não foi possível desistir do serviço.');return}await refresh();onChanged()}
async function withdrawRequest(){if(!currentRequest||!confirm('Desistir deste pedido?'))return;const q=await S.rpc('professional_withdraw_service_request',{p_request_id:currentRequest.id});if(q.error){alert('Não foi possível desistir do pedido.');return}await refresh();onChanged()}
async function completeService(){if(!currentRequest||!confirm('Marcar este serviço como concluído?'))return;const q=await S.rpc('professional_complete_service_request',{p_request_id:currentRequest.id});if(q.error){alert('Não foi possível concluir o serviço.');return}await refresh();onChanged()}
function subscribe(){if(!currentRequest)return;if(channel)S.removeChannel(channel);const id=currentRequest.id;channel=S.channel(`service-chat-${id}`).on('postgres_changes',{event:'*',schema:'public',table:'service_messages',filter:`request_id=eq.${id}`},()=>refresh().catch(console.error)).on('postgres_changes',{event:'*',schema:'public',table:'service_proposals',filter:`request_id=eq.${id}`},()=>refresh().catch(console.error)).on('postgres_changes',{event:'UPDATE',schema:'public',table:'service_requests',filter:`id=eq.${id}`},()=>{refresh().catch(console.error);onChanged()}).subscribe()}
function bind(){if(bound)return;bound=true;$('chatClose')?.addEventListener('click',closeChat);$('chatForm')?.addEventListener('submit',sendMessage);$('proposalForm')?.addEventListener('submit',sendProposal)}
export function initChat({onRequestChange=()=>{}}={}){onChanged=onRequestChange;bind()}
export async function openServiceChat(requestId){const s=getSession();if(!s||!requestId)return;currentRequest={id:requestId};$('chatModal')?.classList.add('open');$('chatMessages').innerHTML='<div class="chat-empty">A carregar conversa…</div>';await refresh();subscribe()}
